//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhouseSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int reservationId { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public Nullable<System.DateTime> dateExpire { get; set; }
        public Nullable<int> payment { get; set; }
        public string status { get; set; }
    }
}
