//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BhouseSys
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userid { get; set; }
        public string userFname { get; set; }
        public string userLname { get; set; }
        public string userAddress { get; set; }
        public string userEmail { get; set; }
        public string userPhone { get; set; }
        public string userName { get; set; }
        public string userPass { get; set; }
        public string userRole { get; set; }
    }
}
